from pydantic import BaseModel, Field
from typing import List, Dict, Optional

class ApplicantRequest(BaseModel):
    income: float = Field(..., ge=0, description="Annual income of the applicant")
    loan_amount: float = Field(..., ge=0, description="Requested loan amount")
    employment_length: float = Field(..., ge=0, le=50, description="Years in active employment")
    existing_debt: float = Field(..., ge=0, description="Total outstanding debt")
    credit_history_length: float = Field(..., ge=0, le=50, description="Years of active credit file history")
    prior_defaults: int = Field(..., ge=0, le=10, description="Number of historical defaults")
    monthly_expenses: float = Field(..., ge=0, description="Monthly living expenses")
    savings_balance: float = Field(..., ge=0, description="Total savings balance in accounts")
    credit_utilization: float = Field(..., ge=0, le=2.0, description="Credit utilization ratio (0.0 to 2.0)")
    transaction_activity: int = Field(..., ge=0, le=200, description="Monthly account transaction count")
    employment_type: str = Field(..., description="Employment category: Salaried, Self-employed, Unemployed")
    employment_notes: Optional[str] = Field("", description="Unstructured text containing job information")

    model_config = {
        "json_schema_extra": {
            "example": {
                "income": 75000.0,
                "loan_amount": 15000.0,
                "employment_length": 5.5,
                "existing_debt": 4000.0,
                "credit_history_length": 8.0,
                "prior_defaults": 0,
                "monthly_expenses": 1200.0,
                "savings_balance": 9500.0,
                "credit_utilization": 0.35,
                "transaction_activity": 25,
                "employment_type": "Salaried",
                "employment_notes": "Permanent position as senior associate at stable design agency."
            }
        }
    }

class FactorItem(BaseModel):
    feature: str
    label: str
    shap_value: float

class PredictResponse(BaseModel):
    default_probability: float = Field(..., description="Calibrated default probability (0.0 to 1.0)")
    risk_score: int = Field(..., description="UI-friendly risk score (0 to 100)")
    decision: str = Field(..., description="Lending recommendation: APPROVE or DECLINE")
    decision_threshold: float = Field(..., description="F1-optimized decision threshold")
    model_version: str = Field(..., description="Model model version")
    top_factors: List[FactorItem] = Field(..., description="TreeSHAP contributions sorted by magnitude")
    top_explanations: List[str] = Field(..., description="Plain-text user-friendly risk explanations")
    underwriting_summary: str = Field(..., description="Natural language narrative generated by LLM/Fallback")
